// Podplane <https://podplane.dev>
// Copyright The Podplane Authors
// SPDX-License-Identifier: Apache-2.0

package v1beta1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// SecretProviderBindingSpec declares which backend keys a workload can mount.
type SecretProviderBindingSpec struct {
	// ProviderName is the cluster-local provider name from Podplane cluster config.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([a-z0-9-]*[a-z0-9])?$`
	ProviderName string `json:"providerName"`

	// MountPath is the absolute workload mount path used by Podplane templates; it is not used for backend path generation.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=255
	// +kubebuilder:validation:Pattern=`^/([A-Za-z0-9_-][A-Za-z0-9._-]*|\.[A-Za-z0-9_-][A-Za-z0-9._-]*|\.\.[A-Za-z0-9._-]+)(/([A-Za-z0-9_-][A-Za-z0-9._-]*|\.[A-Za-z0-9_-][A-Za-z0-9._-]*|\.\.[A-Za-z0-9._-]+))*$`
	MountPath string `json:"mountPath,omitempty"`

	// Items declares the backend keys exposed by the generated SecretProviderClass.
	// +kubebuilder:validation:MinItems=1
	// +listType=map
	// +listMapKey=key
	Items []SecretProviderBindingItem `json:"items"`

	// SyncToKubernetesSecrets declares Kubernetes Secrets generated by the CSI driver.
	// +kubebuilder:validation:Optional
	// +listType=map
	// +listMapKey=secretName
	SyncToKubernetesSecrets []KubernetesSecretSync `json:"syncToKubernetesSecrets,omitempty"`
}

// SecretProviderBindingItem maps a backend key to a mounted file path.
type SecretProviderBindingItem struct {
	// Key is the Podplane-managed backend key name.
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([a-z0-9-]*[a-z0-9])?$`
	Key string `json:"key"`

	// Path is the relative mounted content path inside mountPath. It defaults to key when omitted.
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=255
	// +kubebuilder:validation:Pattern=`^([A-Za-z0-9_-][A-Za-z0-9._-]*|\.[A-Za-z0-9_-][A-Za-z0-9._-]*|\.\.[A-Za-z0-9._-]+)(/([A-Za-z0-9_-][A-Za-z0-9._-]*|\.[A-Za-z0-9_-][A-Za-z0-9._-]*|\.\.[A-Za-z0-9._-]+))*$`
	Path string `json:"path,omitempty"`
}

// KubernetesSecretSync declares a Kubernetes Secret generated by the CSI driver.
type KubernetesSecretSync struct {
	// SecretName is the generated Kubernetes Secret name.
	// +kubebuilder:validation:MaxLength=253
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([-a-z0-9]*[a-z0-9])?$`
	SecretName string `json:"secretName"`

	// Type is the generated Kubernetes Secret type.
	Type string `json:"type"`

	// Labels are copied to the generated Kubernetes Secret.
	// +kubebuilder:validation:Optional
	Labels map[string]string `json:"labels,omitempty"`

	// Annotations are copied to the generated Kubernetes Secret.
	// +kubebuilder:validation:Optional
	Annotations map[string]string `json:"annotations,omitempty"`

	// Data maps mounted object names into Kubernetes Secret data keys.
	// +kubebuilder:validation:MinItems=1
	Data []KubernetesSecretSyncData `json:"data"`
}

// KubernetesSecretSyncData maps a mounted key into a Kubernetes Secret data key.
type KubernetesSecretSyncData struct {
	// FromKey references an item key in this SecretProviderBinding.
	// +kubebuilder:validation:MaxLength=63
	// +kubebuilder:validation:Pattern=`^[a-z0-9]([a-z0-9-]*[a-z0-9])?$`
	FromKey string `json:"fromKey"`

	// Key is the Kubernetes Secret data key.
	// +kubebuilder:validation:MinLength=1
	// +kubebuilder:validation:MaxLength=253
	// +kubebuilder:validation:Pattern=`^[A-Za-z0-9._-]+$`
	Key string `json:"key"`
}

// SecretProviderBindingProviderStatus records the selected provider.
type SecretProviderBindingProviderStatus struct {
	Name string `json:"name,omitempty"`
	Kind string `json:"kind,omitempty"`
}

// SecretProviderClassStatus records the generated SecretProviderClass.
type SecretProviderClassStatus struct {
	Name string `json:"name,omitempty"`
}

// SecretProviderBindingItemStatus records the rendered item path.
type SecretProviderBindingItemStatus struct {
	Key  string `json:"key"`
	Path string `json:"path"`
}

// SecretProviderBindingStatus reports reconciliation state.
type SecretProviderBindingStatus struct {
	Provider            SecretProviderBindingProviderStatus `json:"provider,omitempty"`
	SecretProviderClass SecretProviderClassStatus           `json:"secretProviderClass,omitempty"`
	Items               []SecretProviderBindingItemStatus   `json:"items,omitempty"`
	ObservedGeneration  int64                               `json:"observedGeneration,omitempty"`
	Conditions          []metav1.Condition                  `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=spb
// +kubebuilder:printcolumn:name="Provider",type=string,JSONPath=`.spec.providerName`
// +kubebuilder:printcolumn:name="SecretProviderClass",type=string,JSONPath=`.status.secretProviderClass.name`
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=`.status.conditions[?(@.type=="Ready")].status`
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=`.metadata.creationTimestamp`

// SecretProviderBinding binds a namespace workload to provider-backed secrets.
type SecretProviderBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SecretProviderBindingSpec   `json:"spec,omitempty"`
	Status            SecretProviderBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecretProviderBindingList is a list of SecretProviderBinding objects.
type SecretProviderBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecretProviderBinding `json:"items"`
}
