// Podplane <https://podplane.dev>
// Copyright The Podplane Authors
// SPDX-License-Identifier: Apache-2.0

package v1beta1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

// SecretProviderBindingSpec declares which backend keys a workload can mount.
type SecretProviderBindingSpec struct {
	ProviderName            string                      `json:"providerName"`
	Items                   []SecretProviderBindingItem `json:"items,omitempty"`
	SyncToKubernetesSecrets []KubernetesSecretSync      `json:"syncToKubernetesSecrets,omitempty"`
}

// SecretProviderBindingItem maps a backend key to a mounted file path.
type SecretProviderBindingItem struct {
	Key  string `json:"key"`
	Path string `json:"path,omitempty"`
}

// KubernetesSecretSync declares a Kubernetes Secret generated by the CSI driver.
type KubernetesSecretSync struct {
	SecretName string                     `json:"secretName"`
	Type       string                     `json:"type,omitempty"`
	Data       []KubernetesSecretSyncData `json:"data,omitempty"`
}

// KubernetesSecretSyncData maps a mounted key into a Kubernetes Secret data key.
type KubernetesSecretSyncData struct {
	FromKey string `json:"fromKey"`
	Key     string `json:"key"`
}

// SecretProviderBindingProviderStatus records the selected provider.
type SecretProviderBindingProviderStatus struct {
	Name string `json:"name,omitempty"`
	Kind string `json:"kind,omitempty"`
}

// SecretProviderClassStatus records the generated SecretProviderClass.
type SecretProviderClassStatus struct {
	Name string `json:"name,omitempty"`
}

// SecretProviderBindingItemStatus records the rendered item path.
type SecretProviderBindingItemStatus struct {
	Key  string `json:"key"`
	Path string `json:"path"`
}

// SecretProviderBindingStatus reports reconciliation state.
type SecretProviderBindingStatus struct {
	Provider            SecretProviderBindingProviderStatus `json:"provider,omitempty"`
	SecretProviderClass SecretProviderClassStatus           `json:"secretProviderClass,omitempty"`
	Items               []SecretProviderBindingItemStatus   `json:"items,omitempty"`
	Conditions          []metav1.Condition                  `json:"conditions,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,shortName=spb

// SecretProviderBinding binds a namespace workload to provider-backed secrets.
type SecretProviderBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SecretProviderBindingSpec   `json:"spec,omitempty"`
	Status            SecretProviderBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SecretProviderBindingList is a list of SecretProviderBinding objects.
type SecretProviderBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SecretProviderBinding `json:"items"`
}
