//go:build !ignore_autogenerated

// Podplane <https://podplane.dev>
// Copyright The Podplane Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesSecretSync) DeepCopyInto(out *KubernetesSecretSync) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make([]KubernetesSecretSyncData, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesSecretSync.
func (in *KubernetesSecretSync) DeepCopy() *KubernetesSecretSync {
	if in == nil {
		return nil
	}
	out := new(KubernetesSecretSync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesSecretSyncData) DeepCopyInto(out *KubernetesSecretSyncData) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesSecretSyncData.
func (in *KubernetesSecretSyncData) DeepCopy() *KubernetesSecretSyncData {
	if in == nil {
		return nil
	}
	out := new(KubernetesSecretSyncData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretProviderBinding) DeepCopyInto(out *SecretProviderBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretProviderBinding.
func (in *SecretProviderBinding) DeepCopy() *SecretProviderBinding {
	if in == nil {
		return nil
	}
	out := new(SecretProviderBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretProviderBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretProviderBindingItem) DeepCopyInto(out *SecretProviderBindingItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretProviderBindingItem.
func (in *SecretProviderBindingItem) DeepCopy() *SecretProviderBindingItem {
	if in == nil {
		return nil
	}
	out := new(SecretProviderBindingItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretProviderBindingItemStatus) DeepCopyInto(out *SecretProviderBindingItemStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretProviderBindingItemStatus.
func (in *SecretProviderBindingItemStatus) DeepCopy() *SecretProviderBindingItemStatus {
	if in == nil {
		return nil
	}
	out := new(SecretProviderBindingItemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretProviderBindingList) DeepCopyInto(out *SecretProviderBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretProviderBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretProviderBindingList.
func (in *SecretProviderBindingList) DeepCopy() *SecretProviderBindingList {
	if in == nil {
		return nil
	}
	out := new(SecretProviderBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretProviderBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretProviderBindingProviderStatus) DeepCopyInto(out *SecretProviderBindingProviderStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretProviderBindingProviderStatus.
func (in *SecretProviderBindingProviderStatus) DeepCopy() *SecretProviderBindingProviderStatus {
	if in == nil {
		return nil
	}
	out := new(SecretProviderBindingProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretProviderBindingSpec) DeepCopyInto(out *SecretProviderBindingSpec) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretProviderBindingItem, len(*in))
		copy(*out, *in)
	}
	if in.SyncToKubernetesSecrets != nil {
		in, out := &in.SyncToKubernetesSecrets, &out.SyncToKubernetesSecrets
		*out = make([]KubernetesSecretSync, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretProviderBindingSpec.
func (in *SecretProviderBindingSpec) DeepCopy() *SecretProviderBindingSpec {
	if in == nil {
		return nil
	}
	out := new(SecretProviderBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretProviderBindingStatus) DeepCopyInto(out *SecretProviderBindingStatus) {
	*out = *in
	out.Provider = in.Provider
	out.SecretProviderClass = in.SecretProviderClass
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretProviderBindingItemStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretProviderBindingStatus.
func (in *SecretProviderBindingStatus) DeepCopy() *SecretProviderBindingStatus {
	if in == nil {
		return nil
	}
	out := new(SecretProviderBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretProviderClassStatus) DeepCopyInto(out *SecretProviderClassStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretProviderClassStatus.
func (in *SecretProviderClassStatus) DeepCopy() *SecretProviderClassStatus {
	if in == nil {
		return nil
	}
	out := new(SecretProviderClassStatus)
	in.DeepCopyInto(out)
	return out
}
