# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0

FROM --platform=$BUILDPLATFORM golang:1.26-alpine AS builder
WORKDIR /workspace

RUN apk add --no-cache ca-certificates git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETOS=linux
ARG TARGETARCH=amd64
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
	go build -trimpath -ldflags="-s -w" -o /out/podplane-operator ./cmd/podplane-operator

FROM gcr.io/distroless/static:nonroot
WORKDIR /

COPY --from=builder /out/podplane-operator /usr/bin/podplane-operator

USER nonroot:nonroot

ENTRYPOINT ["/usr/bin/podplane-operator"]
