---
# Podplane <https://podplane.dev>
# Copyright The Podplane Authors
# SPDX-License-Identifier: Apache-2.0
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretproviderbindings.secrets.podplane.dev
spec:
  group: secrets.podplane.dev
  scope: Namespaced
  names:
    plural: secretproviderbindings
    singular: secretproviderbinding
    kind: SecretProviderBinding
    shortNames: [spb]
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion: {type: string}
            kind: {type: string}
            metadata: {type: object}
            spec:
              type: object
              required: [providerName]
              properties:
                providerName: {type: string}
                items:
                  type: array
                  items:
                    type: object
                    required: [key]
                    properties:
                      key: {type: string, pattern: '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$', maxLength: 63}
                      path: {type: string}
                syncToKubernetesSecrets:
                  type: array
                  items:
                    type: object
                    required: [secretName, data]
                    properties:
                      secretName: {type: string}
                      type: {type: string}
                      data:
                        type: array
                        items:
                          type: object
                          required: [fromKey, key]
                          properties:
                            fromKey: {type: string}
                            key: {type: string}
            status:
              type: object
              properties:
                provider:
                  type: object
                  properties:
                    name: {type: string}
                    kind: {type: string}
                secretProviderClass:
                  type: object
                  properties:
                    name: {type: string}
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      key: {type: string}
                      path: {type: string}
                conditions:
                  type: array
                  x-kubernetes-list-type: map
                  x-kubernetes-list-map-keys: [type]
                  items:
                    type: object
                    required: [type, status, reason, message, lastTransitionTime]
                    properties:
                      type: {type: string}
                      status: {type: string}
                      reason: {type: string}
                      message: {type: string}
                      lastTransitionTime: {type: string, format: date-time}
